version: '3'

services:
  mongo:
    image: mongo:latest
    restart: always
    env_file: env_prod.env
    volumes:
      - ./mongo/data/db:/data/db

  telegram_bot:
    build: telegram_bot
    volumes:
      - ./telegram_bot:/usr/src/app
      - ./logs:/logs
    command: python3 bot.py
    env_file: env_prod.env

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    env_file: env_prod.env


