version: '3'

services:
  mongo:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    env_file: env_prod.env
    volumes:
      - ./mongo/data/db:/data/db

  telegram_bot:
    build: telegram_bot
    volumes:
      - ./telegram_bot:/usr/src/app
      - ./logs:/logs
    command: python3 main.py
    env_file: env_prod.env
